version: "3"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: achat
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  spring:
    depends_on:
      - mysqldb
    image: spring
    restart: on-failure
    ports:
      - "8089:8089"

volumes:
  db:
