version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: riadh
       MYSQL_DATABASE: achat
       MYSQL_USER: riadh
       MYSQL_PASSWORD: riadh
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  spring:
    depends_on:
      - mysqldb
    image: spring
    restart: on-failure
    ports:
      - "8089:8089"

volumes:
  db:
